### ISSUE TITLE
Frontmatter processing

### ISSUE THREAD

**Issue by davegardner** [ogdenstudios/eleventy-plugin-markdown-shortcode#1]
This plugin allows me to include footer and aside partials into the page.njk template. However, it doesn't process frontmatter and I need to include a 'title' so that the partials appear in NetlifyCMS with some kind of identifier. If I include frontmatter in the partials it's interpreted as Markdown.

I am new to all this so I might (probably) be missing a simple way to do it. I tried computed data but that doesn't work for titles in NetlifyCMS. Any suggestions? Or is this a feature request?

**Comment by coolsoftwaretyler** [comment]
Hey Dave!

This is the first issue submitted by anyone else. It's been a while since
I've touched this and I'm away from my computer so I don't have anything
helpful for you at the moment.

Glad you're using the plugin. I will dig into this over the weekend and get
back to you shortly.

**Comment by coolsoftwaretyler** [comment]
Hey @davegardner , 

Looking into the plugin here, I built it really just to expose the markdown-it renderer as a shortcode, so I'm only rendering out the contents of the markdown files. 

Can you provide an example of the ideal behavior you'd like to see? I have a couple of ideas about how I could include frontmatter as well, but I don't know if I understand your request 100% yet.

**Comment by davegardner** [comment]
I have several partial md files (2 x asides and a footer) that get included (via your `markdown` plugin) into njk templates. Doing this enables those partials to be easily edited by anyone, without requiring special skills or knowledge. The problem is that those partials need to have a title declared in frontmatter eg `title: footer`. If a title is not defined then when the file is edited in Netlify CMS, it has no identifier -- all the partial files are listed, but with blank titles, so you cannot see which is which. BUT if I define frontmatter in the partial Markdown files, I get identifiers in Netlify CMS ok but the frontmatter is misinterpreted as markdown and produces rubbish at the start of each of the partials.

I am not interested in frontmatter for any purpose than providing a title for NetlifyCMS, so what I really want is for the Markdown plugin to strip the frontmatter before processing it. For example, if the complete raw partial (markdown with frontmatter) file is read into `text` then call this function before processing as markdown:
```js
function stripFrontmatter(text){
    if( ! text || text.indexOf('---') != 0) return text;
        const startOfFrontmatter = 0;
        const endOfFrontmatter = text.indexOf('---', startOfFrontmatter + 3) + 3;
        const plainMd = text.slice(endOfFrontmatter);
        return plainMd;
}
```
So it is not a matter of *including* frontmatter but rather *stripping* it before passing the text to Markdown for normal processing.

I hope that makes it clearer. Ask if you want sample files.

**Comment by coolsoftwaretyler** [comment]
Oh that makes perfect sense and is actually much much easier, I think. Consider it a feature request. I'll figure it out this weekend and ship in the next handful of days. 

Thanks for the additional details. I'll track updates in this issue so you should get notified when it's all set. Have a great day!

**Comment by coolsoftwaretyler** [comment]
@davegardner - thanks again for the issue report. I think I've added your requested functionality, it should be working in v1.1. Let me know if it doesn't resolve your issue.
